[package]
name = "monero-daemon-rpc"
version = "0.1.0"
description = "An interface to a Monero daemon"
license = "MIT"
repository = "https://github.com/monero-oxide/monero-oxide/tree/main/monero-oxide/interface/daemon"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"
rust-version = "1.89"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
std-shims = { version = "0.1.5", default-features = false }

hex = { version = "0.4", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

monero-oxide = { path = "../..", default-features = false }
monero-address = { path = "../../wallet/address", default-features = false }
monero-interface = { path = "..", default-features = false }

monero-epee = { path = "../../epee", default-features = false }

[features]
std = [
  "std-shims/std",

  "hex/std",
  "serde/std",
  "serde_json/std",

  "monero-oxide/std",
  "monero-address/std",
  "monero-interface/std",
]
default = ["std"]
