name: Daily Deny Check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deny:
    name: Run cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Install cargo deny
        shell: bash
        run: cargo +1.92 install cargo-deny --version =0.18.9

      - name: Run cargo deny
        shell: bash
        run: cargo deny -L error --all-features check --hide-inclusion-graph
